# General config
select = [
  "E", "F", "W", # flake8
  "B",           # flake8-bugbear
  "C4",          # flake8-comprehensions
  "C90",         # McCabe cyclomatic complexity
  "DTZ",         # flake8-datetimez
  "EXE",         # flake8-executable
  "FBT",         # flake8-boolean-trap
  "I",           # isort
  "ICN",         # flake8-import-conventions
  "INT",         # flake8-gettext
  "PL",          # Pylint
  "PYI",         # flake8-pyi
  "RET",         # flake8-return
  "RUF",         # Ruff-specific rules
  "S",           # flake8-bandit
  "SIM",         # flake8-simplify
  "T10",         # flake8-debugger
  "TCH",         # flake8-type-checking
  "UP",          # pyupgrade
  "YTT",         # flake8-2020
]
extend-ignore = ["B904", "C408", "RUF100"]
target-version = "py37"
src = ["src"]

[per-file-ignores]
"docs/conf.py" = ["RUF003", "SIM105", "UP032"]
"src/validate_pyproject/api.py" = ["RUF100"]
"src/validate_pyproject/cli.py" = ["C403"]
"src/validate_pyproject/formats.py" = ["S310"]
"src/validate_pyproject/plugins/__init__.py" = ["RUF100"]
"src/validate_pyproject/pre_compile/__init__.py" = ["RUF100"]
"tests/*" = ["PLC1901", "S101"]
"tests/test_plugins.py" = ["C419"]
"tests/test_pre_compile.py" = ["S603"]

# --- Compatibility ---

[isort]
known-third-party = ["validate_pyproject._vendor"]

[pylint]
allow-magic-value-types = ["int", "str"]
