# --- General config ---
select = [
  "E", "F", "W", # flake8
  "B",           # flake8-bugbear
  "C4",          # flake8-comprehensions
  "C90",         # McCabe cyclomatic complexity
  "DTZ",         # flake8-datetimez
  "EXE",         # flake8-executable
  "FBT",         # flake8-boolean-trap
  "I",           # isort
  "ICN",         # flake8-import-conventions
  "INT",         # flake8-gettext
  "PL",          # Pylint
  "PYI",         # flake8-pyi
  "RET",         # flake8-return
  "RUF",         # Ruff-specific rules
  "S",           # flake8-bandit
  "SIM",         # flake8-simplify
  "T10",         # flake8-debugger
  "TCH",         # flake8-type-checking
  "UP",          # pyupgrade
  "YTT",         # flake8-2020
]
ignore = [
  "E501",    # line too long
  "SIM105",  # contextlib.supress (3.7 feature)
]
target-version = "py37"
src = ["src"]

[per-file-ignores]
"tests/*" = ["S"] # Assert okay in tests

# --- Tool-related config ---

[isort]
known-third-party = ["validate_pyproject._vendor"]

[pylint]
allow-magic-value-types = ["int", "str"]
